language: python
python:
  - "3.5"
  - "2.7"
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 5
install:
  -  pip install pip --upgrade
  -  pip install scipy pystan matplotlib
env:
  - TESTTYPE=1 TESTFILE=compare_example.py
  - TESTTYPE=1 TESTFILE=estimate_example.py
  - TESTTYPE=1 TESTFILE=estimate_and_compare_example.py
  - TESTTYPE=1 TESTFILE=estimate_lindley_example.py
matrix:
  include:
  - python: "3.5"
    env: TESTTYPE=0 TESTFILE=test_compare.py
  - python: "3.5"
    env: TESTTYPE=0 TESTFILE=test_lindley_same_bfs.py
  - python: "3.5"
    env: TESTTYPE=0 TESTFILE=test_bfs_mixture_single.py
script:
  - if [ $TESTTYPE = 0 ]; then python -m unittest discover tests $TESTFILE; fi
  - if [ $TESTTYPE = 1 ]; then python $TESTFILE; fi
