language: python
python:
  - "3.5"
  - "2.7"
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 5
install:
  -  pip install pip --upgrade
  -  pip install scipy pystan matplotlib
  -  pip install 'ipython<6'
env:
  - TESTTYPE=0 TESTFILE=test_lindley_same_bfs.py
  - TESTTYPE=1 TESTFILE=compare_example.py
  - TESTTYPE=1 TESTFILE=estimate_example.py
  - TESTTYPE=1 TESTFILE=estimate_and_compare_example.py
  - TESTTYPE=1 TESTFILE=estimate_lindley_example.py
script:
  - if [ $TESTTYPE = 0 ]; then python -m unittest discover tests $TESTFILE; fi
  - if [ $TESTTYPE = 1 ]; then ipython $TESTFILE --matplotlib; fi
